name: fano
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.7 <3.0.0'

dependencies:
  bitcount: ^0.3.0
  path: ^1.8.0
  xpx_chain_sdk: 0.0.7+9

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
